SSAspNet/Models/Pricelist.cs
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace SSAspNet.Model
{
    public class Pricelist : INotifyPropertyChanged
    {        
        protected decimal _carBody;
        protected decimal _carWheels;
        protected decimal _carEngine;
        protected decimal _carBrakes;
        protected decimal _carUndercarriage;
        protected decimal _busSalon;
        protected decimal _busHandsrails;
        protected decimal _busUpholstery;
        protected decimal _pasCarwheelBalancing;
        protected decimal _truckHydraulics;    
        
        public Pricelist() { }        

        public decimal CarBody
        {
            get { return _carBody; }
            set
            {
                _carBody = value;
                OnPropertyChanged("CarBody");
            }
        }

        public decimal CarWheels
        {
            get { return _carWheels; }
            set
            {
                _carWheels = value;
                OnPropertyChanged("CarWheels");
            }
        }

        public decimal CarEngine
        {
            get { return _carEngine; }
            set
            {
                _carEngine = value;
                OnPropertyChanged("CarEngine");
            }
        }

        public decimal CarBrakes
        {
            get { return _carBrakes; }
            set
            {
                _carBrakes = value;
                OnPropertyChanged("CarBrakes");
            }
        }

        public decimal CarUndercarriage
        {
            get { return _carUndercarriage; }
            set
            {
                _carUndercarriage = value;
                OnPropertyChanged("CarUndercarriage");
            }
        }

        public decimal BusSalon
        {
            get { return _busSalon; }
            set
            {
                _busSalon = value;
                OnPropertyChanged("BusSalon");
            }
        }

        public decimal BusHandsrails
        {
            get { return _busHandsrails; }
            set
            {
                _busHandsrails = value;
                OnPropertyChanged("BusHandsrails");
            }
        }

        public decimal BusUpholstery
        {
            get { return _busUpholstery; }
            set
            {
                _busUpholstery = value;
                OnPropertyChanged("BusUpholstery");
            }
        }

        public decimal PasCarwheelBalancing
        {
            get { return _pasCarwheelBalancing; }
            set
            {
                _pasCarwheelBalancing = value;
                OnPropertyChanged("PasCarwheelBalancing");
            }
        }

        public decimal TruckHydraulics
        {
            get { return _truckHydraulics; }
            set
            {
                _truckHydraulics = value;
                OnPropertyChanged("TruckHydraulics");
            }
        } 

        public event PropertyChangedEventHandler PropertyChanged;

        public void OnPropertyChanged([CallerMemberName]string prop = "")
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(prop));
        }
        
    }
}

SSAspNet/Controllers/MainController.cs
using System.Web.Mvc;
using SSAspNet.Model;

namespace SSAspNet.Controllers
{
    public class MainController : Controller
    {
        
        public ViewResult MainMenu()
        {
            return View();
        }

        [HttpGet]
        public ViewResult Pricelist()
        {
            Price price = new Price(1);
            return View(price);
        }
        
        [HttpGet]
        public ViewResult PricelistEdit()
        {
            Price price = new Price(1);                     
            return View(price);
        }

        [HttpPost]
        public ViewResult PricelistEdit(Price price)
        {
            price.EditPrice();           
            return View("MainMenu");
        }

        public ViewResult Info()
        {
            return View();
        }
    }
}

SSAspNet/Controllers/NewOrderController.cs
using SSAspNet.Model;
using System.Web.Mvc;

namespace SSAspNet.Controllers
{
    public class NewOrderController : Controller
    {
        [HttpGet]
        public ActionResult SelectNewOrder()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SelectNewOrder(FormCollection coll)
        {
            string car = coll["Car"].ToString();
            if (car == "PasCar")                           
                return View("~/Views/NewOrder/NewOrderPasCar.cshtml");                            
            else if (car == "Truck")
                return View("~/Views/NewOrder/NewOrderTruck.cshtml");
            else if (car == "Bus")
                return View("~/Views/NewOrder/NewOrderBus.cshtml");
            else
                return View();
        }

        [HttpPost]
        public ActionResult NewOrderPasCar(PasCarServiceStation car)
        {            
            Order order = new Order();
            car.FillOrder(ref order);
            order.AddNewOrder();
            order.GetLastOrderId();
            return View("~/Views/NewOrder/OrderResult.cshtml", order);
        }
        
        [HttpPost]
        public ActionResult NewOrderTruck(TruckCarServiceStation car)
        {
            Order order = new Order();
            car.FillOrder(ref order);
            order.AddNewOrder();
            order.GetLastOrderId();
            return View("~/Views/NewOrder/OrderResult.cshtml", order);
        }        

        [HttpPost]
        public ActionResult NewOrderBus(BusCarServiceStation car)
        {
            Order order = new Order();
            car.FillOrder(ref order);
            order.AddNewOrder();
            order.GetLastOrderId();
            return View("~/Views/NewOrder/OrderResult.cshtml", order);
        }
    }
}

SSAspNet/Controllers/OrdersController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using SSAspNet.Model;

namespace SSAspNet.Controllers
{
    public class OrdersController : Controller
    {

        [HttpGet]
        public ActionResult FindOrderForId()
        {
            return View();
        }

        [HttpPost]
        public ActionResult FindOrderForId(int? id)
        {
            if (id > 0 && id != null)
            {
                Order order = new Order(id);
                if (order.OrderId != null )
                return View("~/Views/Orders/EditOrder.cshtml", order);
            }
            return View("~/Views/Main/MainMenu.cshtml");
        }

        [HttpPost]
        public ActionResult EditOrder(Order order)
        {
            order.EditOrder();
            return View("~/Views/Main/MainMenu.cshtml");
        }

        public ActionResult ActualOrders()
        {
            Order ActualOrders = new Order();
            List<Order> orders = ActualOrders.GetActualOrders();
            return View(orders);
        }

        public ActionResult DoneOrders()
        {
            Order DoneOrders = new Order();
            List<Order> orders = DoneOrders.GetDoneOrders();
            return View(orders);
        }        
    }
}

SSAspNet/Views/Main/Info.cshtml
@{    
    Layout = "~/Views/Shared/_Layout.cshtml";    
}
<page class="Page">

<h2>Information about this web aplication</h2>
<div>
<pre>
Service Station is a test program.

This program is developed using ASP.NET MVC technology and SQL Server.
It's the solution to the task described below.
 
Task: To simulate the work of the Service station.

The following types of vehicles can be serviced at the Service station: passenger car, truck and bus.
The service station diagnoses the following nodes: car bodes, wheels, engines, brakes, undercarriages,
hydraulics (only for truck) bus seats upholstery and handsrails (only for bus).
For each listed node there is a current state from 0 to 100 points (100 points - new, 0 points - not working).

Additional services (at the request of the client):
- wheel balancing for passenger car;
- changing the upholstery of the seats in the cabin for bus.

It is necessary:
- to evaluate the general condition of the vehicle (arithmetic mean for all nodes);
- consider the cost of repair and repair every detail;
- The form on which you can register a arrived car, state it each detail, show the general
condition, the cost of repairs, indicate additional services and display order cost.
Program allows to keep track of the Service Station work, in particular:
 - to enter and save car data;
 - the cost of service stations;
 - to calculate the cost of orders;
 - to calculate the average state of the detail.
</pre>
</div>
</page>

SSAspNet/Views/Main/MainInfo.cshtml
@{    
    Layout = "~/Views/Shared/_Layout.cshtml";    
}
<page class="Page">

<h2>Information about this web aplication</h2>
<pre>
Service Station is a test program.

This program is developed using ASP.NET MVC technology and SQL Server.
It's the solution to the task described below.
 
Task: To simulate the work of the Service station.

The following types of vehicles can be serviced at the Service station: passenger car, truck and bus.
The service station diagnoses the following nodes: car bodes, wheels, engines, brakes, undercarriages,
hydraulics (only for truck) bus seats upholstery and handsrails (only for bus).
For each listed node there is a current state from 0 to 100 points (100 points - new, 0 points - not working).

Additional services (at the request of the client):
- wheel balancing for passenger car;
- changing the upholstery of the seats in the cabin for bus.

It is necessary:
- to evaluate the general condition of the vehicle (arithmetic mean for all nodes);
- consider the cost of repair and repair every detail;
- The form on which you can register a arrived car, state it each detail, show the general
condition, the cost of repairs, indicate additional services and display order cost.
Program allows to keep track of the Service Station work, in particular:
 - to enter and save car data;
 - the cost of service stations;
 - to calculate the cost of orders;
 - to calculate the average state of the detail.
</pre>
</page>

SSAspNet/Views/Main/MainMenu.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";    
}

<page class="Page">

    <div align="center">
        <button type="button" class="buttonMainMenu" onclick="location.href='@Url.Action("SelectNewOrder", "NewOrder")'">New order</button>
        <img src="~/Content/Actual_orders.png" class="imgMainMenu" alt="Actual order" />
    </div>

    <div align="center">
        <button type="button" class="buttonMainMenu" onclick="location.href='@Url.Action("FindOrderForId", "Orders")'">Edit order</button>
        <img src="~/Content/edit.png" alt="Actual order" class="imgMainMenu" />
    </div>

    <div align="center">
        <button type="button" class="buttonMainMenu" onclick="location.href='@Url.Action("ActualOrders", "Orders")'">Actual orders</button>
        <img src="~/Content/New_order.png" alt="Done order" class="imgMainMenu" />
    </div>

    <div align="center">
        <button type="button" class="buttonMainMenu" onclick="location.href='@Url.Action("DoneOrders", "Orders")'">Done orders</button>
        <img src="~/Content/Done_orders.png" alt="New order" class="imgMainMenu" />
    </div>

</page>

SSAspNet/Views/Main/Pricelist.cshtml
@model SSAspNet.Model.Price

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<page class="Page">
    <h2 align="center">Pricelist</h2>

    @using (Html.BeginForm("Pricelist", "Main", FormMethod.Post))
    {
        <table class="tablePricelist" align="center">
            <tr>
                <th>Service</th>
                <th>Cost</th>
                <th></th>
            </tr>
            <tr>
                <td>Car body</td>
                <td>@Model.CarBody</td>
                <td>$</td>
            </tr>
            <tr>
                <td>Car wheels</td>
                <td>@Model.CarWheels</td>
                <td>$</td>
            </tr>
            <tr>
                <td>Car engine</td>
                <td>@Model.CarEngine</td>
                <td>$</td>
            </tr>
            <tr>
                <td>Car brakes</td>
                <td>@Model.CarBrakes</td>
                <td>$</td>
            </tr>
            <tr>
                <td>Car undercarriage</td>
                <td>@Model.CarUndercarriage</td>
                <td>$</td>
            </tr>
            <tr>
                <td>Bus salon</td>
                <td>@Model.BusSalon</td>
                <td>$</td>
            </tr>
            <tr>
                <td>Bus handsrails</td>
                <td>@Model.BusHandsrails</td>
                <td>$</td>
            </tr>
            <tr>
                <td>Bus upholstery</td>
                <td>@Model.BusUpholstery</td>
                <td>$</td>
            </tr>
            <tr>
                <td>Wheel balancing</td>
                <td>@Model.PasCarwheelBalancing</td>
                <td>$</td>
            </tr>
            <tr>
                <td>Truck hydraulics</td>
                <td>@Model.TruckHydraulics</td>
                <td>$</td>
            </tr>
            <tr>
                <td><button type="button" class="buttonCancel" onclick="location.href='@Url.Action("MainMenu", "Main")'">Cancel</button></td>
                <td><button type="button" class="buttonOK" onclick="location.href='@Url.Action("PricelistEdit", "Main")'">Edit</button></td>
            </tr>
        </table>
    }
</page>

SSAspNet/Views/Main/PricelistEdit.cshtml
@model SSAspNet.Model.Price

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<page class="Page">
    <h2 align="center">Pricelist edit</h2>

    @using (Html.BeginForm("PricelistEdit", "Main", FormMethod.Post))
    {
        <table class="tablePricelist" align="center">
            <tr>
                <th>Service</th>
                <th>Cost</th>
                <th></th>
            </tr>
            <tr>
                <td>Car body</td>
                <td>@Html.TextBoxFor(price => price.CarBody)</td>
                <td>$</td>
            </tr>
            <tr>
                <td>Car wheels</td>
                <td>@Html.TextBoxFor(price => price.CarWheels)</td>
                <td>$</td>
            </tr>
            <tr>
                <td>Car engine</td>
                <td>@Html.TextBoxFor(price => price.CarEngine)</td>
                <td>$</td>
            </tr>
            <tr>
                <td>Car brakes</td>
                <td>@Html.TextBoxFor(price => price.CarBrakes)</td>
                <td>$</td>
            </tr>
            <tr>
                <td>Car undercarriage</td>
                <td>@Html.TextBoxFor(price => price.CarUndercarriage)</td>
                <td>$</td>
            </tr>
            <tr>
                <td>Bus salon</td>
                <td>@Html.TextBoxFor(price => price.BusSalon)</td>
                <td>$</td>
            </tr>
            <tr>
                <td>Bus handsrails</td>
                <td>@Html.TextBoxFor(price => price.BusHandsrails)</td>
                <td>$</td>
            </tr>
            <tr>
                <td>Bus upholstery</td>
                <td>@Html.TextBoxFor(price => price.BusUpholstery)</td>
                <td>$</td>
            </tr>
            <tr>
                <td>Wheel balancing</td>
                <td>@Html.TextBoxFor(price => price.PasCarwheelBalancing)</td>
                <td>$</td>
            </tr>
            <tr>
                <td>Truck hydraulics</td>
                <td>@Html.TextBoxFor(price => price.TruckHydraulics)</td>
                <td>$</td>
            </tr>
            <tr>
                <td><button type="button" class="buttonCancel" onclick="location.href='@Url.Action("MainMenu", "Main")'">Cancel</button></td>
                <td><input type="submit" class="buttonOK" value="Save" id="price"/></td>
            </tr>
        </table>
    }
</page>